---
# tasks file for ufw
- name: Install ufw
  apt: package=ufw state=present

- name: Configure ufw defaults
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  notify:
    - restart ufw

- name: Configure ufw rules
  ufw: rule={{ item.rule }} port={{ item.port }} from_ip={{ item.from_ip }}
  with_items:
    - { port: 22, rule: allow, from_ip: '89.187.169.117' }
    - { port: 22, rule: allow, from_ip: '89.187.169.117' }
    - { port: 22, rule: allow, from_ip: '89.187.169.117' }

- name: Enable ufw logging
  ufw: logging=on

- name: Enable ufw
  ufw: state=enabled